<div id="footer">  
	<div class="text_footer">
	    <a href="#">About</a> | <a href="#">Help</a>
	    <h5>SQUAREFACE 2015</h5>
	</div>	
</div>
  
<script src="../js/jquery.min.js"></script>  
<script src="../js/bootstrap.min.js"></script>  
<script src="../js/jquery-ui.js"></script>
<script src="../js/LiveValidation.js"></script> 
<script src="../js/functions.js"></script>
<script src="../js/jquery.panelslider.min.js"></script>
<script src="../js/jquery.magnific-popup.js"></script>
<script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyChEZKZvF-cZPsd-9DXB4jHvxXg1NoV9bo&sensor=true"></script>
<script src="../js/location.js"></script>
<script src="../js/owl.carousel.js"></script>
<script src="../js/perfect-scrollbar.jquery.js"></script>
<script src="../js/star-rating.min.js"></script>
<script src="http://localhost:8090/socket.io/socket.io.js"></script> <!-- This script is generated by a socket.io package -->
  
<script> 
	$(document).ready(function(){	
	    //maginific popup's
	    $('.ajax-popup-link').magnificPopup({
		    type: 'ajax',
		    closeOnBgClick:false,
		    closeOnContentClick:false,
		    closeBtnInside:false
		});
		
		$('.ajax-category').magnificPopup({
		    type: 'ajax',
		    closeOnBgClick:false,
		    closeOnContentClick:false,
		    closeBtnInside:false
		});
		
		$('.ajax-promotion').magnificPopup({
		    type: 'ajax',
		    closeOnBgClick:false,
		    closeOnContentClick:false,
		    closeBtnInside:false
		});
		
		//continue register user
		$('.continue_user').magnificPopup({
		    type: 'ajax',
		    closeOnBgClick:false,
		    closeOnContentClick:false,
		});
		
		$(".continue_user").click();
		
		//label of search----------------
		var tags = new LiveValidation('tags');
		tags.add(Validate.Presence);
		
		var tags_mobile = new LiveValidation('tags_mobile');
		tags_mobile.add(Validate.Presence);		
	
	    //panel notifications--------------------------
		$('#left-panel-link').panelslider();	
		$('#close_notifications').click(function() {
			$.panelslider.close();
		});
		
		/*scrollbar notifications*/
	    $('.scroll_activity').perfectScrollbar();
	
		//panel friends--------------------------------
		$('#right-panel-link').panelslider({side: 'right'});		
		$('#close_friends').click(function() {
			$.panelslider.close();
		});
		
		//socket's-----
		var socket = io.connect('http://localhost:8090'); //This variable is a new instance of socket , this var is individualy instanced for each user in the app
        socket.on('connect',function(data){
            console.log("Welcome user");
        });
              
        socket.on("showme",function(data){ // the client call this function , when the server respond a petition.
            console.log("Append");
            $("#messages").append("<div>"+data.username+"</div>");    
        });
		
	});	
	
	//function acordeon friends
	$(function() {
		$( "#accordion" ).accordion({
			collapsible: true,
	  		heightStyle: "fill",
			active: false
		});
    });
	
</script>
  
</body>
</html>
















